[font]
size = 15.0

[font.offset]
x = 0
y = 0

[window]
decorations = "Full"
dynamic_padding = true
resize_increments = true
opacity = 1.0

[window.dimensions]
columns = 115
lines = 40

[window.padding]
x = 5
y = 5

[cursor]
style = { blinking = "Always", shape = "Block" }
blink_timeout = 0

