import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[font]
size = 15.0

[font.bold]
family = "Hack Nerd Font"

[font.italic]
family = "Hack Nerd Font"

[font.normal]
family = "Hack Nerd Font"

[font.offset]
x = 0
y = 0

[window]
decorations = "Full"
dynamic_padding = true
resize_increments = true
opacity = 0.9

[window.dimensions]
columns = 115
lines = 40

[window.padding]
x = 5
y = 5

[cursor]
style = { blinking = "Always", shape = "Block" }
blink_timeout = 0
